<?php
session_start();
require_once __DIR__ . '/../config/db.php';
$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header("Location: ../auth/login.php");
    exit;
}

$start_date = $_GET['start_date'] ?? date('Y-m-01');
$end_date   = $_GET['end_date']   ?? date('Y-m-t');

$stmt = $conn->prepare("
    SELECT
        b.id            AS booking_id,
        b.transaction_id,
        u.username      AS customer_name,
        u.email         AS customer_email,
        s.name          AS service_name,
        s.price,
        b.booking_date,
        b.booking_time,
        b.payment_status
    FROM bookings b
    JOIN services s ON b.service_id = s.id
    JOIN users    u ON b.customer_id = u.id
    WHERE b.payment_status = 'paid'
      AND b.booking_date BETWEEN ? AND ?
    ORDER BY b.booking_date DESC, b.id DESC
");
$stmt->execute([$start_date, $end_date]);
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

$filename = 'sunflower_payment_report_' . $start_date . '_to_' . $end_date . '.csv';

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Pragma: no-cache');
header('Expires: 0');

$out = fopen('php://output', 'w');

// BOM for Excel UTF-8
fwrite($out, "\xEF\xBB\xBF");

// Meta header rows
fputcsv($out, ['SUNFLOWER MASSAGE & RELAXATION CENTER']);
fputcsv($out, ['Payment Report']);
fputcsv($out, ['Period:', $start_date . ' to ' . $end_date]);
fputcsv($out, ['Generated:', date('d M Y, h:i A')]);
fputcsv($out, ['Generated By:', $_SESSION['username'] ?? 'Admin']);
fputcsv($out, []);

// Column headers
fputcsv($out, [
    'Booking ID',
    'Transaction ID',
    'Customer Name',
    'Customer Email',
    'Service',
    'Amount (RM)',
    'Booking Date',
    'Booking Time',
    'Payment Status',
]);

// Data rows
$total = 0;
foreach ($rows as $row) {
    fputcsv($out, [
        '#' . $row['booking_id'],
        $row['transaction_id'] ?: '-',
        $row['customer_name'],
        $row['customer_email'],
        $row['service_name'],
        number_format($row['price'], 2),
        date('d M Y', strtotime($row['booking_date'])),
        $row['booking_time'] ? date('h:i A', strtotime($row['booking_time'])) : '-',
        strtoupper($row['payment_status']),
    ]);
    $total += (float)$row['price'];
}

// Summary footer
fputcsv($out, []);
fputcsv($out, ['', '', '', '', 'TOTAL REVENUE:', 'RM ' . number_format($total, 2)]);
fputcsv($out, ['', '', '', '', 'TOTAL TRANSACTIONS:', count($rows)]);

fclose($out);
exit;